import React, { useState, useEffect, useRef } from 'react';
import imageService from './services/imageServiceProvider';
import { useDispatch, useSelector } from 'react-redux';
import { addLink } from './features/assistantSlice';
import { storeImageLink } from './utils/imageLinkStore';
import {
  downloadImage,
  fileExtensionFromDataUrl,
  isDataImageUrl,
  openImageInNewTab,
  resolveImageLinkUrl,
  revokeBlobUrl,
  toDisplayUrl,
} from './utils/imageUrl';

const ENGINE_LABELS = {
  openai: 'OpenAI',
  imagen: 'Gemini',
};

const ENGINE_FULL_NAMES = {
  openai: 'OpenAI GPT Image',
  imagen: 'Google Gemini Image',
};

const ENGINE_LINK_SUFFIX = {
  openai: ' (OpenAI)',
  imagen: ' (Gemini)',
};

const LAST_IMAGERY_KEY = 'rf-imagery-last';

function wrapDataUrl(dataUrl) {
  return isDataImageUrl(dataUrl) ? { dataUrl, url: toDisplayUrl(dataUrl) } : null;
}

function lastPairFromStorage() {
  try {
    const parsed = JSON.parse(localStorage.getItem(LAST_IMAGERY_KEY) || 'null');
    if (!parsed) return { openai: null, imagen: null };
    return {
      openai: wrapDataUrl(parsed.openai),
      imagen: wrapDataUrl(parsed.imagen),
    };
  } catch {
    return { openai: null, imagen: null };
  }
}

function persistLastImagery(pair) {
  try {
    localStorage.setItem(LAST_IMAGERY_KEY, JSON.stringify({
      openai: pair.openai?.dataUrl || null,
      imagen: pair.imagen?.dataUrl || null,
    }));
  } catch {
    // Quota — sessionStorage via storeImageLink still covers this tab.
  }
}

/** Newest cached image for an engine, from the links panel store (newest first). */
function lastCachedEngineImage(links, engine) {
  const suffix = ENGINE_LINK_SUFFIX[engine];
  if (!suffix || !Array.isArray(links)) return null;
  for (const link of links) {
    if (!link?.isImage) continue;
    const text = typeof link.text === 'string' ? link.text : '';
    if (!text.endsWith(suffix)) continue;
    const dataUrl = resolveImageLinkUrl(link);
    if (!isDataImageUrl(dataUrl)) continue;
    return wrapDataUrl(dataUrl);
  }
  return null;
}

function initialImagery(links) {
  const fromLinks = {
    openai: lastCachedEngineImage(links, 'openai'),
    imagen: lastCachedEngineImage(links, 'imagen'),
  };
  if (fromLinks.openai || fromLinks.imagen) return fromLinks;
  return lastPairFromStorage();
}

const SegControl = ({ label, name, value, options, onChange, disabled }) => (
  <div className="field">
    <label id={`${name}-l`}>{label}</label>
    <div className="seg" role="radiogroup" aria-labelledby={`${name}-l`}>
      {options.map((opt) => (
        <label key={opt.value} className="seg-opt">
          <input
            type="radio"
            name={name}
            checked={value === opt.value}
            disabled={disabled}
            onChange={() => onChange(opt.value)}
          />
          {opt.label}
        </label>
      ))}
    </div>
  </div>
);

const ComparisonPanel = ({ engine, aspect, image, error, isGenerating, onViewImage, onDownload }) => (
  <div>
    <p className="engine-label">{ENGINE_LABELS[engine]}</p>
    <div className={`imagery-frame aspect-${aspect}`}>
      {!image && !error && !isGenerating && <span className="imagery-empty">Awaiting prompt</span>}
      {isGenerating && !image && !error && <span className="spinner" />}
      {error && !image && <span className="imagery-error">{error}</span>}
      {image && (
        <button
          type="button"
          className="imagery-image-button"
          onClick={() => onViewImage(image.dataUrl || image.url, ENGINE_FULL_NAMES[engine])}
          aria-label={`Open ${ENGINE_FULL_NAMES[engine]} preview in a new tab`}
          title={image.revisedPrompt || undefined}
        >
          <img src={image.url} alt={`Generated by ${ENGINE_FULL_NAMES[engine]}`} />
        </button>
      )}
    </div>
    {image && (
      <div className="imagery-actions">
        <button
          type="button"
          className="btn btn-ghost"
          onClick={() => {
            const src = image.dataUrl || image.url;
            const ext = fileExtensionFromDataUrl(src);
            onDownload(src, `${engine}-generated.${ext}`);
          }}
        >
          Download
        </button>
      </div>
    )}
  </div>
);

const AiImageryForm = () => {
  const dispatch = useDispatch();
  const persistentLinks = useSelector((state) => state.assistant.persistentLinks);
  const [prompt, setPrompt] = useState('');
  const [aspect, setAspect] = useState('square');
  const [quality, setQuality] = useState('standard');
  const [style, setStyle] = useState('natural');
  const [isGenerating, setIsGenerating] = useState(false);
  const [images, setImages] = useState(() => initialImagery(persistentLinks));
  const [errors, setErrors] = useState({ openai: null, imagen: null, global: null });
  const resultsRef = useRef(null);
  const skipScrollRef = useRef(true);

  const revokeCurrentImages = () => {
    Object.values(images).forEach((img) => {
      if (img?.url) revokeBlobUrl(img.url);
    });
  };

  const handleViewImage = (url, label) => {
    openImageInNewTab(url, label);
  };

  const handleDownloadImage = (url, filename) => {
    downloadImage(url, filename);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsGenerating(true);
    setErrors({ openai: null, imagen: null, global: null });
    revokeCurrentImages();
    setImages({ openai: null, imagen: null });

    try {
      const { openai, imagen, errors: engineErrors } = await imageService.generateComparison({
        prompt,
        aspect,
        quality,
        style,
      });

      setImages({ openai, imagen });
      persistLastImagery({ openai, imagen });
      setErrors({
        openai: engineErrors.openai ? 'OpenAI generation failed.' : null,
        imagen: engineErrors.imagen ? 'Gemini image generation failed.' : null,
        global: !openai && !imagen ? 'Both engines failed. Please try again.' : null,
      });

      if (openai?.dataUrl) {
        const imageId = storeImageLink(openai.dataUrl);
        dispatch(addLink({
          url: `#image:${imageId}`,
          imageId,
          text: `${prompt} (OpenAI)`,
          isImage: true,
        }));
      }
      if (imagen?.dataUrl) {
        const imageId = storeImageLink(imagen.dataUrl);
        dispatch(addLink({
          url: `#image:${imageId}`,
          imageId,
          text: `${prompt} (Gemini)`,
          isImage: true,
        }));
      }
    } catch {
      setErrors({ openai: null, imagen: null, global: 'Error generating images. Please try again.' });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter') {
      e.preventDefault();
    }
  };

  useEffect(
    () => () => {
      [images.openai?.url, images.imagen?.url].forEach((url) => url && revokeBlobUrl(url));
    },
    [images],
  );

  useEffect(() => {
    if (skipScrollRef.current) {
      skipScrollRef.current = false;
      return;
    }
    if ((images.openai || images.imagen || errors.global) && resultsRef.current) {
      setTimeout(() => {
        resultsRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 500);
    }
  }, [images, errors.global]);

  return (
    <div>
      <h2 className="screen-h2">One prompt, two engines.</h2>
      <p className="screen-sub">
        The same prompt goes to OpenAI GPT Image and Google Gemini Image, side by side.
      </p>
      <form onSubmit={handleSubmit} className="imagery-form">
        <textarea
          className="input"
          rows="2"
          value={prompt}
          disabled={isGenerating}
          onKeyDown={handleKeyDown}
          onChange={(e) => setPrompt(e.target.value)}
          placeholder="Describe an image. Ex: a red apple floating in space."
          aria-label="Image prompt"
          required
        />
        <div className="imagery-controls">
          <SegControl
            label="Aspect"
            name="aspect"
            value={aspect}
            disabled={isGenerating}
            onChange={setAspect}
            options={[
              { value: 'square', label: 'Square' },
              { value: 'landscape', label: 'Landscape' },
              { value: 'portrait', label: 'Portrait' },
            ]}
          />
          <SegControl
            label="Quality"
            name="quality"
            value={quality}
            disabled={isGenerating}
            onChange={setQuality}
            options={[
              { value: 'standard', label: 'Standard' },
              { value: 'hd', label: 'HD' },
            ]}
          />
          <SegControl
            label="Style"
            name="style"
            value={style}
            disabled={isGenerating}
            onChange={setStyle}
            options={[
              { value: 'natural', label: 'Natural' },
              { value: 'vivid', label: 'Vivid' },
            ]}
          />
          <span className="spacer" />
          <button type="submit" className="btn btn-primary" disabled={isGenerating}>
            {isGenerating ? <span className="spinner" /> : 'Generate'}
          </button>
        </div>
      </form>
      <div className="imagery-grid" ref={resultsRef}>
        <ComparisonPanel
          engine="openai"
          aspect={aspect}
          image={images.openai}
          error={errors.openai}
          isGenerating={isGenerating}
          onViewImage={handleViewImage}
          onDownload={handleDownloadImage}
        />
        <ComparisonPanel
          engine="imagen"
          aspect={aspect}
          image={images.imagen}
          error={errors.imagen}
          isGenerating={isGenerating}
          onViewImage={handleViewImage}
          onDownload={handleDownloadImage}
        />
      </div>
      {errors.global && <p className="error-message">{errors.global}</p>}
    </div>
  );
};

export default AiImageryForm;
