import React, { useState, useEffect, useRef } from 'react';
import imageService from './services/imageServiceProvider';
import { useDispatch } from 'react-redux';
import { addLink } from './features/assistantSlice';
import { downloadImage, openImageInNewTab, revokeBlobUrl } from './utils/imageUrl';

const ENGINE_LABELS = {
  openai: 'OpenAI GPT Image',
  imagen: 'Google Imagen',
};

const ComparisonPanel = ({ engine, image, error, isGenerating, onViewImage, onDownload }) => (
  <div className="image-compare-panel">
    <h3 className="image-compare-engine">{ENGINE_LABELS[engine]}</h3>
    {isGenerating && !image && !error && (
      <div className="image-compare-loading">
        <span className="spinner"></span>
        <p>Generating…</p>
      </div>
    )}
    {error && !image && <p className="image-compare-error">{error}</p>}
    {image && (
      <div className="image-compare-result">
        <button
          type="button"
          className="image-compare-frame"
          onClick={() => onViewImage(image.dataUrl || image.url, ENGINE_LABELS[engine])}
          aria-label={`Open ${ENGINE_LABELS[engine]} preview in a new tab`}
        >
          <img className="ai-imagery-image" src={image.url} alt={`Generated by ${ENGINE_LABELS[engine]}`} />
          {image.revisedPrompt && <div className="overlay-text">{image.revisedPrompt}</div>}
        </button>
        <div className="image-compare-actions">
          <button
            type="button"
            className="image-action-btn"
            onClick={() => onDownload(image.dataUrl || image.url, `${engine}-generated.png`)}
          >
            Download
          </button>
        </div>
      </div>
    )}
  </div>
);

const AiImageryForm = () => {
  const dispatch = useDispatch();
  const [prompt, setPrompt] = useState('');
  const [aspect, setAspect] = useState('square');
  const [quality, setQuality] = useState('standard');
  const [style, setStyle] = useState('natural');
  const [isGenerating, setIsGenerating] = useState(false);
  const [images, setImages] = useState({ openai: null, imagen: null });
  const [errors, setErrors] = useState({ openai: null, imagen: null, global: null });
  const resultsRef = useRef(null);
  const messagesContainerRef = useRef(null);

  const revokeCurrentImages = () => {
    Object.values(images).forEach((img) => {
      if (img?.url) revokeBlobUrl(img.url);
    });
  };

  const handleViewImage = (url, label) => {
    openImageInNewTab(url, label);
  };

  const handleDownloadImage = (url, filename) => {
    downloadImage(url, filename);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsGenerating(true);
    setErrors({ openai: null, imagen: null, global: null });
    revokeCurrentImages();
    setImages({ openai: null, imagen: null });

    try {
      const { openai, imagen, errors: engineErrors } = await imageService.generateComparison({
        prompt,
        aspect,
        quality,
        style,
      });

      setImages({ openai, imagen });
      setErrors({
        openai: engineErrors.openai ? 'OpenAI generation failed.' : null,
        imagen: engineErrors.imagen ? 'Imagen generation failed.' : null,
        global: !openai && !imagen ? 'Both engines failed. Please try again.' : null,
      });

      if (openai?.dataUrl) {
        dispatch(addLink({ url: openai.dataUrl, dataUrl: openai.dataUrl, text: `${prompt} (OpenAI)`, isImage: true }));
      }
      if (imagen?.dataUrl) {
        dispatch(addLink({ url: imagen.dataUrl, dataUrl: imagen.dataUrl, text: `${prompt} (Imagen)`, isImage: true }));
      }
    } catch {
      setErrors({ openai: null, imagen: null, global: 'Error generating images. Please try again.' });
    } finally {
      setIsGenerating(false);
    }
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter') {
      e.preventDefault();
    }
  };

  const adjustConversationHeight = () => {
    const headerHeight = document.querySelector('.navbar')?.offsetHeight || 0;
    const footerHeight = document.querySelector('.footer')?.offsetHeight || 0;
    const headerH1 = document.querySelector('.playground-h1')?.offsetHeight || 0;
    const availableHeight = window.innerHeight - headerHeight - headerH1 - footerHeight;
    if (messagesContainerRef.current) {
      messagesContainerRef.current.style.height = `${availableHeight - 43}px`;
    }
  };

  useEffect(() => {
    window.addEventListener('resize', adjustConversationHeight);
    adjustConversationHeight();
    return () => window.removeEventListener('resize', adjustConversationHeight);
  }, []);

  useEffect(
    () => () => {
      [images.openai?.url, images.imagen?.url].forEach((url) => url && revokeBlobUrl(url));
    },
    [images],
  );

  useEffect(() => {
    if ((images.openai || images.imagen || errors.global) && resultsRef.current) {
      setTimeout(() => {
        resultsRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
      }, 500);
    }
  }, [images, errors.global]);

  return (
    <div className="ai-imagery">
      <div className={`form-container ${isGenerating ? 'generating' : ''}`} ref={messagesContainerRef}>
        <h2>AI Imagery</h2>
        <p className="image-compare-intro">
          Enter one prompt to compare OpenAI GPT Image and Google Imagen side by side.
        </p>
        <form onSubmit={handleSubmit} className="ai-imagery-form">
          <div className="form-left">
            <label htmlFor="prompt" className="form-label">
              Image Prompt:
            </label>
            <textarea
              id="prompt"
              value={prompt}
              disabled={isGenerating}
              onKeyDown={handleKeyDown}
              onChange={(e) => setPrompt(e.target.value)}
              rows="4"
              placeholder="Describe an image to generate. Ex: A red apple floating in space."
              required
              className="form-textarea"
            />
          </div>

          <div className="form-right">
            <div className="form-group">
              <label htmlFor="aspect" className="form-label">
                Aspect ratio:
              </label>
              <select
                id="aspect"
                value={aspect}
                disabled={isGenerating}
                onChange={(e) => setAspect(e.target.value)}
                className="form-select"
              >
                <option value="square">Square</option>
                <option value="landscape">Landscape</option>
                <option value="portrait">Portrait</option>
              </select>
            </div>

            <div className="form-group">
              <label htmlFor="quality" className="form-label">
                Quality (OpenAI):
              </label>
              <select
                id="quality"
                value={quality}
                disabled={isGenerating}
                onChange={(e) => setQuality(e.target.value)}
                className="form-select"
              >
                <option value="standard">Standard</option>
                <option value="hd">HD</option>
              </select>
            </div>

            <div className="form-group">
              <label htmlFor="style" className="form-label">
                Style:
              </label>
              <select
                id="style"
                value={style}
                disabled={isGenerating}
                onChange={(e) => setStyle(e.target.value)}
                className="form-select"
              >
                <option value="natural">Natural</option>
                <option value="vivid">Vivid</option>
              </select>
            </div>
          </div>

          <div className="form-button-container">
            <button type="submit" className="form-button submit" disabled={isGenerating}>
              {isGenerating ? <span className="spinner"></span> : 'Generate Images'}
            </button>
          </div>
        </form>

        <div className="response image-compare-results" ref={resultsRef}>
          <div className={`image-compare-grid image-compare-grid--${aspect}`}>
            <ComparisonPanel
              engine="openai"
              image={images.openai}
              error={errors.openai}
              isGenerating={isGenerating}
              onViewImage={handleViewImage}
              onDownload={handleDownloadImage}
            />
            <ComparisonPanel
              engine="imagen"
              image={images.imagen}
              error={errors.imagen}
              isGenerating={isGenerating}
              onViewImage={handleViewImage}
              onDownload={handleDownloadImage}
            />
          </div>
          {errors.global && <p className="error-message">{errors.global}</p>}
        </div>
      </div>
    </div>
  );
};

export default AiImageryForm;
